name: Rust CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Run tests
        run: cargo test --all-features --verbose

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: test

    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-musl

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build release
        run: cross build --release --target ${{ matrix.target }}

      - name: Package binary
        env:
          TARGET: ${{ matrix.target }}
        run: |
          mkdir dist

          cp target/${TARGET}/release/C_boots dist/C_boots

          tar -C dist -czf C_boots-${GITHUB_REF_NAME}-${TARGET}.tar.gz C_boots

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: C_boots-${{ github.ref_name }}-${{ matrix.target }}.tar.gz

  publish:
    name: Publish GitHub Release
    needs: release
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          files: release-artifacts/*.tar.gz
